version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
        ports:
            - 80:80
            - 443:443
        environment:
            - "DB_CONNECTION=${DB_CONNECTION}"
            - "DB_HOST=${DB_HOST}"
#            - "DB_PORT=${DB_PORT}"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
        networks:
            - laravel

    db:
        image: postgres:14
        restart: always
        environment:
            - "POSTGRES_USER=${DB_USERNAME}"
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_DB=${DB_DATABASE}"
            - "POSTGRES_TEST_DB=${DB_TEST_DATABASE}"
        ports:
            - 5432:5432
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data/
        networks:
            - laravel

    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./.data/redis:/data
        networks:
            - laravel

networks:
    laravel:
